const DB_NAME='finance-recruiting-terminal'; const DB_VERSION=2;
const DEFAULT_PROFILE={university:'Lehigh University',major:'Finance',gpa:2.81,graduationYear:2029,workAuthorization:'US Authorized',locations:['New York, NY','Seattle, WA','Boston, MA'],careerInterests:['Investment Banking','Private Credit','Wealth Management','Asset Management','Valuation','Corporate Finance','FP&A','Financial Consulting'],experience:'',skills:'',alertThreshold:75,fitWeight:.46,careerWeight:.36,nycBonus:12,seattleBonus:8,bostonBonus:5,resumeName:''};
const STATUSES=['Interested','Applying','Applied','Online Assessment','HireVue','First Round','Second Round','Superday / Final Round','Offer','Rejected','Withdrawn','Ghosted'];
let db, view='dashboard', opportunities=[], employers=[], health={}, profile=DEFAULT_PROFILE, applications=[], saved=new Set(), localEmployers=[];

function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains('kv'))d.createObjectStore('kv');if(!d.objectStoreNames.contains('applications'))d.createObjectStore('applications',{keyPath:'id'});if(!d.objectStoreNames.contains('saved'))d.createObjectStore('saved',{keyPath:'id'});if(!d.objectStoreNames.contains('files'))d.createObjectStore('files',{keyPath:'id'});if(!d.objectStoreNames.contains('employers_local'))d.createObjectStore('employers_local',{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function get(store,key){return new Promise((res,rej)=>{const r=tx(store).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(store,val,key){return new Promise((res,rej)=>{const r=key===undefined?tx(store,'readwrite').put(val):tx(store,'readwrite').put(val,key);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function all(store){return new Promise((res,rej)=>{const r=tx(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function del(store,key){return new Promise((res,rej)=>{const r=tx(store,'readwrite').delete(key);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=d=>d?new Date(d).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'—';
const fmtDateTime=d=>d?new Date(d).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—';
const hoursSince=d=>d?(Date.now()-new Date(d).getTime())/36e5:9999;
function locationRank(loc=''){const x=loc.toLowerCase();if(x.includes('new york'))return 1;if(x.includes('seattle'))return 2;if(x.includes('boston'))return 3;return 4}
function scoreClass(n){return n>=75?'good':n>=55?'mid':'low'}
function containsAny(text,terms){const t=(text||'').toLowerCase();return terms.some(x=>t.includes(x.toLowerCase()))}
function deriveScores(o){
  const text=[o.title,o.description,o.category,o.required_qualifications,o.preferred_qualifications].join(' ').toLowerCase();
  let fit=58, career=o.career_value_seed??60; const reasons=[]; const cautions=[];
  const gpa=o.gpa||{}; if(gpa.type==='hard'&&Number.isFinite(+gpa.minimum)){if(profile.gpa<+gpa.minimum){fit-=42;cautions.push(`Explicit GPA minimum ${gpa.minimum} exceeds current ${profile.gpa.toFixed(2)}`)}else{fit+=8;reasons.push('Meets explicit GPA minimum')}} else if(gpa.type==='preferred'&&Number.isFinite(+gpa.minimum)){if(profile.gpa<+gpa.minimum){fit-=8;cautions.push(`Preferred GPA ${gpa.minimum} is above current GPA`)}else fit+=4}else if(gpa.type==='none'){fit+=8;reasons.push('No stated GPA minimum')}
  if((o.eligible_graduation_years||[]).length){if(o.eligible_graduation_years.includes(+profile.graduationYear)){fit+=15;reasons.push('Graduation year matches')}else{fit-=45;cautions.push('Graduation year appears outside stated eligibility')}}
  if((o.work_authorization||'').toLowerCase().includes('no sponsorship')&&profile.workAuthorization==='Sponsorship Required'){fit-=50;cautions.push('Work authorization conflict')}
  if(containsAny(text,['finance','investment','valuation','credit','banking','financial','treasury','fp&a'])){fit+=7;career+=5;reasons.push('Strong finance relevance')}
  const experienceTokens=(profile.experience+' '+profile.skills).toLowerCase().split(/[^a-z0-9+#.]+/).filter(x=>x.length>3);const matches=[...new Set(experienceTokens.filter(t=>text.includes(t)))].slice(0,5);if(matches.length){fit+=Math.min(10,matches.length*2);reasons.push(`Profile overlap: ${matches.join(', ')}`)}
  const category=(o.category||'').toLowerCase();if(containsAny(category,['investment banking','private credit','private equity','equity research','valuation','transaction','asset management']))career+=12;if(containsAny(text,['modeling','valuation','transaction','deal','underwriting','financial analysis','investment research']))career+=10;
  fit=Math.max(0,Math.min(100,Math.round(fit)));career=Math.max(0,Math.min(100,Math.round(career)));
  const loc=locationRank(o.location);const locBonus=loc===1?profile.nycBonus:loc===2?profile.seattleBonus:loc===3?profile.bostonBonus:0;if(loc<4)reasons.push(`${['','NYC','Seattle','Boston'][loc]} location priority`);
  const recency=Math.max(0,12-Math.floor(hoursSince(o.first_detected_at)/12));if(hoursSince(o.first_detected_at)<24)reasons.push('Detected within the last 24 hours');
  let urgency=0;if(o.deadline){const days=(new Date(o.deadline)-Date.now())/864e5;if(days>=0&&days<=3){urgency=8;reasons.push('Deadline is close')}else if(days<=7)urgency=4}
  let priority=Math.round(fit*profile.fitWeight+career*profile.careerWeight+locBonus+recency*.55+urgency);priority=Math.max(0,Math.min(100,priority));
  let classification=fit>=78?'HIGH PROBABILITY':fit>=58?'REALISTIC':fit>=25?'REACH':'NOT ELIGIBLE';if(cautions.some(x=>/explicit GPA|Graduation year|authorization conflict/i.test(x))&&fit<30)classification='NOT ELIGIBLE';
  return {...o,fit,career,priority,classification,reasons,cautions};
}
function actionItems(){const out=[];for(const a of applications){const o=opportunities.find(x=>x.id===a.opportunityId)||a.snapshot||{};for(const [field,label] of [['assessmentDeadline','Assessment due'],['interviewDate','Interview'],['followUpDate','Follow up']]){if(a[field]){const hrs=(new Date(a[field])-Date.now())/36e5;if(hrs>=-12&&hrs<=72)out.push({when:a[field],label,company:o.company,role:o.title})}}}for(const o0 of opportunities){const o=deriveScores(o0);if(o.deadline){const hrs=(new Date(o.deadline)-Date.now())/36e5;if(hrs>=0&&hrs<=48&&!applications.some(a=>a.opportunityId===o.id))out.push({when:o.deadline,label:'Application deadline',company:o.company,role:o.title})}}return out.sort((a,b)=>new Date(a.when)-new Date(b.when))}
function card(o0){const o=deriveScores(o0);const app=applications.find(a=>a.opportunityId===o.id);return `<article class="opp-card"><div><div class="company">${esc(o.company)}</div><div class="role">${esc(o.title)}</div><span class="pill">${esc(o.location||'Unknown')}</span><span class="pill">${esc(o.category||'Other Finance')}</span><span class="pill">${esc(o.classification)}</span></div><div><div class="score ${scoreClass(o.fit)}">${o.fit}</div><div class="score-label">Fit</div></div><div><div class="score ${scoreClass(o.career)}">${o.career}</div><div class="score-label">Career value</div></div><div><div class="score ${scoreClass(o.priority)}">${o.priority}</div><div class="score-label">Priority</div></div><div><div>${fmtDate(o.date_posted)}</div><div class="score-label">Posted</div></div><div><div>${fmtDateTime(o.first_detected_at)}</div><div class="score-label">Detected</div></div><div class="card-actions"><a class="btn" href="${esc(o.apply_url)}" target="_blank" rel="noopener">Apply</a><button class="btn secondary save-btn" data-id="${esc(o.id)}">${saved.has(o.id)?'Saved':'Save'}</button><button class="btn secondary apply-btn" data-id="${esc(o.id)}">${app?'Edit':'Mark Applied'}</button></div><div class="explain"><b>Why:</b> ${esc([...o.reasons,...o.cautions.map(x=>'Caution: '+x)].slice(0,5).join(' • ')||'Limited structured qualification data; score is conservative.')} <span class="pill">GPA: ${esc(o.gpa?.type||'unknown')}${o.gpa?.minimum?` ${o.gpa.minimum}`:''}</span></div></article>`}
function section(title,items,limit=8){return `<section class="section"><div class="section-head"><h2>${title}</h2><span class="muted small">${items.length}</span></div>${items.length?`<div class="feed">${items.slice(0,limit).map(card).join('')}</div>`:'<div class="empty">No confirmed opportunities in this section yet.</div>'}</section>`}
function dashboard(){const scored=opportunities.filter(o=>o.status==='Open').map(deriveScores).sort((a,b)=>b.priority-a.priority);const today=scored.filter(o=>hoursSince(o.first_detected_at)<24);const actions=actionItems();const apps=applications.filter(a=>!['Rejected','Withdrawn'].includes(a.status));return `<div class="container"><div class="kpi-grid">${[['Open',scored.length],['New today',today.length],['Priority ≥75',scored.filter(o=>o.priority>=75).length],['Applications',applications.length],['Action required',actions.length],['Healthy sources',health.healthy||0]].map(([l,v])=>`<div class="kpi"><div class="value">${v}</div><div class="label">${l}</div></div>`).join('')}</div>${health.last_cycle?`<div class="notice">Monitoring feed last cycle: ${fmtDateTime(health.last_cycle)}. Health shown here comes from the actual monitor output file, not a UI timer.</div>`:''}${section('🔴 NEW TODAY',today)}${section('⭐ HIGHEST PRIORITY',scored)}${section('🗽 NYC',scored.filter(o=>locationRank(o.location)===1))}${section('🌲 SEATTLE',scored.filter(o=>locationRank(o.location)===2))}${section('🏙 BOSTON',scored.filter(o=>locationRank(o.location)===3))}${section('🌎 STRONG OPPORTUNITIES ELSEWHERE',scored.filter(o=>locationRank(o.location)===4).sort((a,b)=>b.career-a.career))}<section class="section"><div class="section-head"><h2>⚠️ ACTION REQUIRED</h2><span class="muted small">${actions.length}</span></div>${actions.length?`<div class="table-wrap"><table><thead><tr><th>When</th><th>Action</th><th>Company</th><th>Role</th></tr></thead><tbody>${actions.map(a=>`<tr><td>${fmtDateTime(a.when)}</td><td>${esc(a.label)}</td><td>${esc(a.company)}</td><td>${esc(a.role)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No upcoming actions.</div>'}</section>${section('📋 MY APPLICATIONS',apps.map(a=>a.snapshot||opportunities.find(o=>o.id===a.opportunityId)).filter(Boolean),6)}${matrix(scored)}</div>`}
function matrix(scored){const markets=['NYC','Seattle','Boston','Other'];const cats=['Investment Banking','Wealth Management','Corporate Finance','Private Credit','Valuation','Consulting'];const locFn=(o,m)=>m==='NYC'?locationRank(o.location)===1:m==='Seattle'?locationRank(o.location)===2:m==='Boston'?locationRank(o.location)===3:locationRank(o.location)===4;return `<section class="section"><div class="section-head"><h2>LOCATION × CAREER MATRIX</h2></div><div class="table-wrap"><table class="matrix"><thead><tr><th>Market</th>${cats.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${markets.map(m=>`<tr><th>${m}</th>${cats.map(c=>{const n=scored.filter(o=>locFn(o,m)&&(o.category||'').toLowerCase().includes(c.toLowerCase().replace('corporate finance','corporate'))).length;return `<td class="clickable matrix-cell" data-market="${m}" data-cat="${c}">${n}</td>`}).join('')}</tr>`).join('')}</tbody></table></div></section>`}
function opportunitiesView(){return `<div class="container"><div class="filters"><input id="q" placeholder="Search company / role"/><select id="loc"><option value="">All locations</option><option>NYC</option><option>Seattle</option><option>Boston</option><option>Other</option></select><select id="cat"><option value="">All categories</option>${[...new Set(opportunities.map(o=>o.category).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="class"><option value="">All fit classes</option>${['HIGH PROBABILITY','REALISTIC','REACH','NOT ELIGIBLE'].map(x=>`<option>${x}</option>`).join('')}</select><select id="gpaFilter"><option value="">Any GPA rule</option><option value="hard">Hard GPA</option><option value="preferred">Preferred GPA</option><option value="none">No GPA listed</option><option value="unknown">Unknown</option></select><select id="sort"><option value="priority">Priority</option><option value="detected">Newest detected</option><option value="posted">Newest posted</option><option value="fit">Fit</option><option value="career">Career value</option><option value="deadline">Deadline</option><option value="company">Company</option></select></div><div id="oppFeed" class="feed"></div></div>`}
function renderOppFeed(){const el=document.querySelector('#oppFeed');if(!el)return;const q=document.querySelector('#q').value.toLowerCase(),loc=document.querySelector('#loc').value,cat=document.querySelector('#cat').value,cl=document.querySelector('#class').value,gf=document.querySelector('#gpaFilter').value,sort=document.querySelector('#sort').value;let rows=opportunities.filter(o=>o.status==='Open').map(deriveScores).filter(o=>(!q||(`${o.company} ${o.title}`).toLowerCase().includes(q))&&(!cat||o.category===cat)&&(!cl||o.classification===cl)&&(!gf||(o.gpa?.type||'unknown')===gf)&&(!loc||(loc==='NYC'?locationRank(o.location)===1:loc==='Seattle'?locationRank(o.location)===2:loc==='Boston'?locationRank(o.location)===3:locationRank(o.location)===4)));const s={priority:(a,b)=>b.priority-a.priority,detected:(a,b)=>new Date(b.first_detected_at)-new Date(a.first_detected_at),posted:(a,b)=>new Date(b.date_posted||0)-new Date(a.date_posted||0),fit:(a,b)=>b.fit-a.fit,career:(a,b)=>b.career-a.career,deadline:(a,b)=>new Date(a.deadline||'2999')-new Date(b.deadline||'2999'),company:(a,b)=>a.company.localeCompare(b.company)};rows.sort(s[sort]);el.innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">No matches.</div>'}
function applicationsView(){return `<div class="container"><div class="section-head"><h2>APPLICATION TRACKER</h2><span class="muted">Private: stored in this browser's IndexedDB</span></div>${applications.length?`<div class="table-wrap"><table><thead><tr><th>Company</th><th>Role</th><th>Location</th><th>Status</th><th>Date applied</th><th>Next action</th><th></th></tr></thead><tbody>${applications.map(a=>{const o=a.snapshot||{};const next=a.assessmentDeadline||a.interviewDate||a.followUpDate;return `<tr><td>${esc(o.company)}</td><td>${esc(o.title)}</td><td>${esc(o.location)}</td><td><span class="status">${esc(a.status)}</span></td><td>${fmtDateTime(a.dateApplied)}</td><td>${fmtDateTime(next)}</td><td><button class="btn secondary app-edit" data-id="${esc(a.opportunityId)}">Edit</button></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">No applications recorded yet. Use “Mark Applied” on an opportunity.</div>'}</div>`}
function employersView(){return `<div class="container"><div class="section-head"><div><h2>EMPLOYER / SOURCE DATABASE</h2><span class="muted">${employers.length} total sources</span></div><button class="btn" id="addEmployerBtn">Add employer</button></div><div class="table-wrap"><table><thead><tr><th>Employer</th><th>Type</th><th>ATS</th><th>Monitoring</th><th>Status</th><th>Careers</th></tr></thead><tbody>${employers.map(e=>`<tr><td>${esc(e.company)}</td><td>${esc(e.company_type)}</td><td>${esc(e.ats||'Unknown')}</td><td>${esc(e.monitoring_method||'—')}</td><td><span class="status ${esc((e.monitoring_status||'unknown').toLowerCase().replaceAll(' ','-'))}">${esc(e.monitoring_status||'Not Yet Configured')}</span></td><td>${e.careers_url?`<a href="${esc(e.careers_url)}" target="_blank" rel="noopener">Official site</a>`:'—'}</td></tr>`).join('')}</tbody></table></div></div>`}
function healthView(){const rows=health.sources||[];return `<div class="container"><div class="kpi-grid">${[['Total employers',health.total_employers||employers.length],['Actively monitored',health.actively_monitored||0],['Healthy',health.healthy||0],['Failing',health.failing||0],['Manual',health.manual||0],['Not configured',health.not_configured||0]].map(([l,v])=>`<div class="kpi"><div class="value">${v}</div><div class="label">${l}</div></div>`).join('')}</div><div class="notice">A failed source is treated as a monitoring failure, not as “zero jobs.” Previous opportunities are preserved.</div><div class="table-wrap"><table><thead><tr><th>Employer</th><th>ATS</th><th>Last check</th><th>Last success</th><th>Result</th><th>Errors</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.company)}</td><td>${esc(r.ats||'')}</td><td>${fmtDateTime(r.last_check)}</td><td>${fmtDateTime(r.last_success)}</td><td><span class="status ${r.ok?'healthy':'failing'}">${r.ok?'Healthy':'Failing'}</span></td><td>${esc(r.error||'')}</td></tr>`).join('')}</tbody></table></div></div>`}
function calendarView(){const now=new Date(),y=now.getFullYear(),m=now.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),start=first.getDay();const ev=[];for(const o of opportunities){if(o.deadline)ev.push({d:new Date(o.deadline),t:`Deadline: ${o.company}`});if(o.first_detected_at)ev.push({d:new Date(o.first_detected_at),t:`Opened: ${o.company}`})}for(const a of applications){for(const [f,l] of [['assessmentDeadline','Assessment'],['interviewDate','Interview'],['followUpDate','Follow up']])if(a[f])ev.push({d:new Date(a[f]),t:`${l}: ${a.snapshot?.company||''}`})}let cells='';for(let i=0;i<start;i++)cells+='<div></div>';for(let d=1;d<=last.getDate();d++){const dayEv=ev.filter(e=>e.d.getFullYear()===y&&e.d.getMonth()===m&&e.d.getDate()===d);cells+=`<div class="day"><div class="num">${d}</div>${dayEv.map(e=>`<div class="event">${esc(e.t)}</div>`).join('')}</div>`}return `<div class="container"><div class="section-head"><h2>RECRUITING CALENDAR — ${now.toLocaleString(undefined,{month:'long',year:'numeric'})}</h2></div><div class="calendar-grid">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class="muted small">${x}</div>`).join('')}${cells}</div></div>`}
function render(){const app=document.querySelector('#app');app.innerHTML=view==='dashboard'?dashboard():view==='opportunities'?opportunitiesView():view==='applications'?applicationsView():view==='calendar'?calendarView():view==='health'?healthView():employersView();document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===view));wireDynamic();if(view==='opportunities')renderOppFeed()}
function wireDynamic(){const add=document.querySelector('#addEmployerBtn');if(add)add.onclick=()=>{document.querySelector('#employerForm').reset();document.querySelector('#employerDialog').showModal()};document.querySelectorAll('.save-btn').forEach(b=>b.onclick=async()=>{if(saved.has(b.dataset.id)){await del('saved',b.dataset.id);saved.delete(b.dataset.id)}else{await put('saved',{id:b.dataset.id,savedAt:new Date().toISOString()});saved.add(b.dataset.id)}render()});document.querySelectorAll('.apply-btn,.app-edit').forEach(b=>b.onclick=()=>openApplication(b.dataset.id));document.querySelectorAll('.filters input,.filters select').forEach(x=>x.addEventListener('input',renderOppFeed));document.querySelectorAll('.matrix-cell').forEach(c=>c.onclick=()=>{view='opportunities';render();const loc=document.querySelector('#loc');if(loc)loc.value=c.dataset.market==='NYC'?'NYC':c.dataset.market;const cat=document.querySelector('#cat');if(cat&&[...cat.options].some(o=>o.value===c.dataset.cat))cat.value=c.dataset.cat;renderOppFeed()})}
function openApplication(id){const o=opportunities.find(x=>x.id===id);const existing=applications.find(a=>a.opportunityId===id)||{id:'app-'+id,opportunityId:id,status:'Applied',dateApplied:new Date().toISOString(),snapshot:o};const f=document.querySelector('#applicationForm');f.status.innerHTML=STATUSES.map(s=>`<option>${s}</option>`).join('');for(const el of f.elements){if(el.name&&existing[el.name]!=null){if(el.type==='datetime-local')el.value=new Date(existing[el.name]).toISOString().slice(0,16);else el.value=existing[el.name]}}f.opportunityId.value=id;document.querySelector('#applicationDialog').showModal()}
async function saveApplication(){const f=document.querySelector('#applicationForm'),id=f.opportunityId.value,o=opportunities.find(x=>x.id===id);const prev=applications.find(a=>a.opportunityId===id)||{};const obj={...prev,id:'app-'+id,opportunityId:id,snapshot:o||prev.snapshot,status:f.status.value,dateApplied:f.dateApplied.value?new Date(f.dateApplied.value).toISOString():null,recruiter:f.recruiter.value,recruiterContact:f.recruiterContact.value,referral:f.referral.value,assessmentDeadline:f.assessmentDeadline.value?new Date(f.assessmentDeadline.value).toISOString():null,interviewDate:f.interviewDate.value?new Date(f.interviewDate.value).toISOString():null,followUpDate:f.followUpDate.value?new Date(f.followUpDate.value).toISOString():null,networkingContacts:f.networkingContacts.value,interviewNotes:f.interviewNotes.value,notes:f.notes.value,offerInfo:f.offerInfo.value,updatedAt:new Date().toISOString()};await put('applications',obj);applications=await all('applications');document.querySelector('#applicationDialog').close();render()}
function fillProfile(){const f=document.querySelector('#profileForm');for(const [k,v] of Object.entries(profile)){if(f[k])f[k].value=Array.isArray(v)?v.join(', '):v}document.querySelector('#resumeStatus').textContent=profile.resumeName?`Stored locally: ${profile.resumeName}`:'No resume stored in this browser yet.'}
async function saveProfile(){const f=document.querySelector('#profileForm');profile={...profile,university:f.university.value,major:f.major.value,gpa:+f.gpa.value||0,graduationYear:+f.graduationYear.value||2029,workAuthorization:f.workAuthorization.value,locations:f.locations.value.split(',').map(x=>x.trim()).filter(Boolean),careerInterests:f.careerInterests.value.split(',').map(x=>x.trim()).filter(Boolean),experience:f.experience.value,skills:f.skills.value,alertThreshold:+f.alertThreshold.value||75,fitWeight:+f.fitWeight.value||.46,careerWeight:+f.careerWeight.value||.36,nycBonus:+f.nycBonus.value||12,seattleBonus:+f.seattleBonus.value||8,bostonBonus:+f.bostonBonus.value||5};const file=f.resume.files?.[0];if(file){profile.resumeName=file.name;await put('files',{id:'resume',name:file.name,type:file.type,updatedAt:new Date().toISOString(),blob:file})}await put('kv',profile,'profile');document.querySelector('#profileDialog').close();render()}
async function blobToDataURL(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(blob)})}
async function exportAll(){const resume=await get('files','resume');const data={version:2,exportedAt:new Date().toISOString(),profile,applications,localEmployers,opportunities,monitorHealth:health,saved:[...saved],resumeMetadata:resume?{name:resume.name,type:resume.type,updatedAt:resume.updatedAt,dataUrl:await blobToDataURL(resume.blob)}:null};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`finance-recruiting-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
async function importAll(file){const data=JSON.parse(await file.text());if(data.profile){profile={...DEFAULT_PROFILE,...data.profile};await put('kv',profile,'profile')}for(const a of data.applications||[])await put('applications',a);for(const id of data.saved||[])await put('saved',{id,savedAt:new Date().toISOString()});for(const e of data.localEmployers||[])await put('employers_local',e);if(data.resumeMetadata?.dataUrl){const r=await fetch(data.resumeMetadata.dataUrl);await put('files',{id:'resume',name:data.resumeMetadata.name,type:data.resumeMetadata.type,updatedAt:data.resumeMetadata.updatedAt,blob:await r.blob()})}applications=await all('applications');saved=new Set((await all('saved')).map(x=>x.id));localEmployers=await all('employers_local');employers=[...employers.filter(e=>!e.local),...localEmployers.map(e=>({...e,local:true}))];render()}
async function saveEmployer(){const f=document.querySelector('#employerForm');const id='local-'+crypto.randomUUID();const e={id,company:f.company.value.trim(),company_type:f.company_type.value.trim()||'Unknown',industry:f.industry.value.trim()||'Unknown',ats:f.ats.value,careers_url:f.careers_url.value.trim(),relevant_categories:f.relevant_categories.value.split(',').map(x=>x.trim()).filter(Boolean),office_locations:f.office_locations.value.split(';').map(x=>x.trim()).filter(Boolean),monitoring_method:'Manual Monitoring Required until adapter is configured',monitoring_status:'Manual Monitoring',local:true};await put('employers_local',e);localEmployers=await all('employers_local');employers=[...employers.filter(x=>!x.local),...localEmployers];document.querySelector('#employerDialog').close();render()}
async function boot(){db=await openDB();profile={...DEFAULT_PROFILE,...(await get('kv','profile')||{})};applications=await all('applications');saved=new Set((await all('saved')).map(x=>x.id));localEmployers=await all('employers_local');const load=async(p,f)=>{try{const r=await fetch(p,{cache:'no-store'});if(!r.ok)throw new Error(r.status);return await r.json()}catch(e){return f}};[opportunities,employers,health]=await Promise.all([load('data/jobs.json',[]),load('data/employers.json',[]),load('data/monitor_health.json',{})]);employers=[...employers,...localEmployers];document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{view=t.dataset.view;render()});document.querySelector('#profileBtn').onclick=()=>{fillProfile();document.querySelector('#profileDialog').showModal()};document.querySelector('#saveProfileBtn').onclick=e=>{e.preventDefault();saveProfile()};document.querySelector('#saveApplicationBtn').onclick=e=>{e.preventDefault();saveApplication()};document.querySelector('#saveEmployerBtn').onclick=e=>{e.preventDefault();saveEmployer()};document.querySelector('#exportBtn').onclick=exportAll;document.querySelector('#importBtn').onclick=()=>document.querySelector('#importFile').click();document.querySelector('#importFile').onchange=e=>e.target.files[0]&&importAll(e.target.files[0]);if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});render()}
boot();
